---  
- hosts: localhost  
  gather_facts: no  
  connection: local   
  vars:  
    #your region  
    region: ap-southeast-1    
  tasks:  
    - name: EC2 provisioning with general purpose EBS volume 
      ec2:
        region: "{{ region }}"  
        key_name: awx 
        instance_type: t2.micro  
        image: ami-061eb2b23f9f8839c
        group: sg_webserver_apsydney
        volumes:
          - device_name: /dev/sda1
            device_type: gp2
            volume_size: 100
            delete_on_termination: true
