---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: ap-southeast-1   
  tasks:  
    - name: EC2 basic provisioning  
      ec2:
        region: "{{ region }}"  
        key_name: kubetest
        instance_type: t1.micro  
        image: ami-03b6f27628a4569c8      
        group: default
        instance_tags:  
          Name: "web{{ item }}"  
      with_sequence: count=1
