---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: ap-southeast-2    
  tasks:  
    - name: EC2 basic provisioning  
      ec2:
        region: "{{ region }}"  
        key_name: kubetest 
        instance_type: t1.micro  
        image: ami-03b6f27628a4569c8  
        wait: yes    
        group: All
        instance_tags:  
          group: All
        exact_count: 3  
        count_tag:  
          group: All
