---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    region: 'ap-southeast-1'
  tasks:
    - name: Stop Existing instances using Instance ID's
      ec2:
        region: "{{ region }}"
        wait: true
        instance_ids: [ 'i-0bbc1b87aba50be2b' ]
        state: 'stopped' 
